name: MJob
author: 민
version: 민잘생긴 버전
api: 
- 4.0.0
- 3.3.0
- 3.2.5
- 3.0.0
- 3.1.0
- 3.3.1
- 3.3.2
- 3.3.3

main: MJob\MJob

commands:
 직업:
  description: "직업 UI를 엽니다 §b|| §7made by min"
  default: true
 직업월드:
  description: "사용할 수 있는 월드를 수정합니다 §b|| §7made by min"
  default: true
